# Generated by Django 2.0.3 on 2018-03-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.IntegerField(unique=True)),
                ('user_name', models.CharField(max_length=10, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user_admin', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
