# Generated by Django 2.0.3 on 2018-03-26 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=10, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user_type', models.CharField(default='Student', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Myclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.IntegerField()),
                ('class_admin', models.CharField(max_length=30)),
                ('is_activity', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('class_member', models.OneToOneField(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'myclass',
            },
        ),
    ]
