# Generated by Django 2.0.3 on 2018-03-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180325_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='Student', max_length=32),
        ),
    ]
