# Generated by Django 2.0.3 on 2018-03-25 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_myclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='class_member',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
