# Generated by Django 2.0.3 on 2018-04-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclass',
            name='class_member',
        ),
        migrations.DeleteModel(
            name='Myclass',
        ),
    ]
