# Generated by Django 2.0.3 on 2018-03-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_classhomework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classhomework',
            old_name='problem',
            new_name='problem_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user_name',
        ),
        migrations.AddField(
            model_name='classhomework',
            name='problem_title',
            field=models.CharField(default='a', max_length=30),
        ),
    ]
