# Generated by Django 2.0.3 on 2018-03-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20180329_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
