# Generated by Django 2.0.3 on 2018-03-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20180313_0955'),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('problem', models.ForeignKey(on_delete=False, to='problem.Problem')),
            ],
        ),
    ]
