# Generated by Django 2.0.3 on 2018-03-29 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20180326_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('homework_item', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='classhomework',
            name='homework_item',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classhomework',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
