# Generated by Django 2.0.3 on 2018-03-31 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20180331_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='problem',
            new_name='problem_id',
        ),
    ]
