# Generated by Django 2.0.3 on 2018-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_auto_20180331_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='homework_item',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
