# Generated by Django 2.0.3 on 2018-04-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_auto_20180403_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classhomework',
            name='homework_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='submission.Homework_item'),
        ),
    ]
