language: python
python: 
  - "3.6"
install:
  - pip install -r requirements.txt
sudo: required
dist: precise
addons:
    postgresql: "9.5"
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py runserver
