language: python
python: 
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py runserver
