# Generated by Django 2.0.3 on 2018-03-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20180329_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework_item',
            name='homework_item_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classhomework',
            name='homework_item',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
