# Generated by Django 2.0.3 on 2018-04-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0010_submission_homework_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classhomework',
            name='problem_id',
            field=models.ForeignKey(on_delete=False, to='problem.Problem'),
        ),
    ]
