# Generated by Django 2.0.3 on 2018-04-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0013_auto_20180403_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classhomework',
            name='homework_item',
        ),
        migrations.RemoveField(
            model_name='classhomework',
            name='problem_id',
        ),
        migrations.DeleteModel(
            name='ClassHomework',
        ),
        migrations.DeleteModel(
            name='Homework_item',
        ),
    ]
