# Generated by Django 2.0.3 on 2018-06-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0014_auto_20180410_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='real_time',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
