# Generated by Django 2.0.3 on 2018-05-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('created_user_id', models.IntegerField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('is_public', models.BooleanField()),
            ],
            options={
                'db_table': 'Announcement',
            },
        ),
    ]
