# Generated by Django 2.0.3 on 2018-04-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0002_auto_20180313_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('problem_title', models.CharField(default='a', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Homework_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('homework_item', models.CharField(max_length=20)),
                ('homework_item_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='classhomework',
            name='homework_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='homework.Homework_item'),
        ),
        migrations.AddField(
            model_name='classhomework',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
