# Generated by Django 2.0.3 on 2018-03-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='languages',
        ),
        migrations.AlterField(
            model_name='problem',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tag',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_case_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
