# Generated by Django 2.0.3 on 2018-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20180313_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
