# Generated by Django 2.0.3 on 2018-05-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20180521_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
