# Generated by Django 2.0.3 on 2018-06-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20180522_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='simple_input',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='simple_output',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
