# Generated by Django 2.0.3 on 2018-06-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20180602_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='_id',
            field=models.CharField(db_index=True, max_length=24, unique=True),
        ),
    ]
