# Generated by Django 2.0.3 on 2018-06-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClassIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'myclassindex',
            },
        ),
        migrations.AlterField(
            model_name='myclass',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclass.MyClassIndex'),
        ),
    ]
