# Generated by Django 2.0.3 on 2018-06-04 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0002_auto_20180604_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclass',
            name='class_admin',
        ),
        migrations.RemoveField(
            model_name='myclass',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='myclass',
            name='is_activity',
        ),
        migrations.AddField(
            model_name='myclassindex',
            name='class_admin',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myclassindex',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
