# Generated by Django 2.0.3 on 2018-06-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0003_auto_20180604_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclass',
            name='is_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myclassindex',
            name='class_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
